/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as HistoryImport } from './routes/history'
import { Route as DebugImport } from './routes/debug'
import { Route as AchievementsImport } from './routes/achievements'
import { Route as IndexImport } from './routes/index'
import { Route as RequestsIndexImport } from './routes/requests.index'
import { Route as HistoryRunIdImport } from './routes/history_.$runId'

// Create/Update Routes

const HistoryRoute = HistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRoute,
} as any)

const DebugRoute = DebugImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRoute,
} as any)

const AchievementsRoute = AchievementsImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const RequestsIndexRoute = RequestsIndexImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRoute,
} as any)

const HistoryRunIdRoute = HistoryRunIdImport.update({
  id: '/history_/$runId',
  path: '/history/$runId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsImport
      parentRoute: typeof rootRoute
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryImport
      parentRoute: typeof rootRoute
    }
    '/history_/$runId': {
      id: '/history_/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof HistoryRunIdImport
      parentRoute: typeof rootRoute
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/debug': typeof DebugRoute
  '/history': typeof HistoryRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/requests': typeof RequestsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/debug': typeof DebugRoute
  '/history': typeof HistoryRoute
  '/history/$runId': typeof HistoryRunIdRoute
  '/requests': typeof RequestsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/debug': typeof DebugRoute
  '/history': typeof HistoryRoute
  '/history_/$runId': typeof HistoryRunIdRoute
  '/requests/': typeof RequestsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/debug'
    | '/history'
    | '/history/$runId'
    | '/requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/debug'
    | '/history'
    | '/history/$runId'
    | '/requests'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/debug'
    | '/history'
    | '/history_/$runId'
    | '/requests/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  DebugRoute: typeof DebugRoute
  HistoryRoute: typeof HistoryRoute
  HistoryRunIdRoute: typeof HistoryRunIdRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  DebugRoute: DebugRoute,
  HistoryRoute: HistoryRoute,
  HistoryRunIdRoute: HistoryRunIdRoute,
  RequestsIndexRoute: RequestsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/achievements",
        "/debug",
        "/history",
        "/history_/$runId",
        "/requests/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/achievements": {
      "filePath": "achievements.tsx"
    },
    "/debug": {
      "filePath": "debug.tsx"
    },
    "/history": {
      "filePath": "history.tsx"
    },
    "/history_/$runId": {
      "filePath": "history_.$runId.tsx"
    },
    "/requests/": {
      "filePath": "requests.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
