[package]
name = "types"
version = "0.1.0"
edition = "2024"

[dependencies]
ts-rs = "10.1"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4.41", features = ["serde"] }
thiserror = "2"
sqlx = { version = "0.8" }
reqlang = { git = "https://github.com/testingrequired/reqlang.git", rev = "6dafa75f24c0ff520339c522235d952efc2b5206" }

[features]
bundle_types = []

[[bin]]
name = "bundle_types"
path = "src/bin/bundle.rs"
required-features = ["bundle_types"]
