[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
server = { path = "../server" }
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
clap = { version = "4.5.32", features = ["derive"] }
tao = "0.34.5"
wry = "0.52.1"

[[bin]]
name = "reqlang-web"
path = "src/main.rs"
