app-name := "rust-web-app"

default:
    @just --list

# Delete build artifacts for server and client
clean:
    rm -rf playwright-report
    rm -rf test-suites

# Build the code
build:
    echo 'No build'

# Build the code for release
build-release:
    echo 'No build for release'

# Run the release server for the e2e test to use
run-server:
    cd ../target/release && ./reqlang-web-browser --db 'sqlite::memory:' --port=3000 --open false

# Run all tests
test:
    npm run test